import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";

export default function Home() {
  return (
    <div>
      <Head>
        <title> TO DO USING SSR </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="bg-indigo-500">
          
          <div className="text-3xl font-bold text-center underline">
            {" "}
            TO DO USING SSR
          </div>
          <div className="image">
            <Image
              src={"/todo.jpg"}
              width={200}
              height={200}
              class="absolute"
              layout="responsive"
            />
          </div>
        </nav>
      </main>
      <div>
        <Link href="/list">
          <button
            className="bg-gray-500 text-white py-3 px-6 rounded text-center 
        tracking-wider rounded-full hover:bg-blue-500"
          >
            DISPLAY LIST
          </button>
        </Link>
      </div>
    </div>
  );
}
